### ISSUE TITLE
Some more info on the Match Expression

### ISSUE THREAD

**Issue by christiaanlouw1** [Kaian/sngrep#305]
I was looking at Issue #24 and #25. I would like to use a match expression that filers only registation on certain numbers.

At the moment we would do something like sngrep -l 500 -R '123456|56789'

Using this sngrep '^(REGISTER)'   , I can filter for registrations but how can I also add a specific number as to not see all the registrations?

**Comment by Kaian** [comment]
Hi @christiaanlouw1 

Hmm it seams the match expression is applied line by line through the payload so using regexp wildcards  (.*)  doesn't seem to help.
Not the most efficient option, but what about using filter.method setting. This is the same as selecting only REGISTER in the filter screen.  

```
echo set filter.methods REGISTER > register_sngreprc
sngrep -l 500 -R '(123456|56789)'`
```

**Comment by christiaanlouw1** [comment]
Will this be a perminent thing?

Will it change our normal sngreps we do like sngrep -c 123456 or sngrep 123456?
Will those normal sngrep still work to display EVERYTHING or INVITES?

**Comment by christiaanlouw1** [comment]
Have you considered adding -m flag as mentioned in #25 ?

**Comment by Kaian** [comment]
> Will this be a permanent thing?

Nope, this will only apply if you use that configuration file with `-f` flag. The rest of executions wont use that filter option.

> Have you considered adding -m flag as mentioned in #25 ?

For current 1.x version, I prefer changing the regexp matching to "match the whole payload" so "^REGISTER.*other.*words" could work rather than adding the mentioned option.

But I would try to consider METHOD filtering from command line for future releases.

Regards!

**Comment by Kaian** [comment]
Above commit should do the trick. If you want to compile sngrep with PCRE support, you should be able to _grep_ your dialogs using

```
sngrep -l 500 -R '^REGISTER.*'(123456|56789)'
```

I'll add this for 1.4.7

Regards!

**Comment by christiaanlouw1** [comment]
Thank you. We will use the extra sngreprpc config file for now and look forward to the enhancement in future release.
